### ISSUE TITLE
Collaborate to integrate with eslint/vscode plugins

### ISSUE THREAD

**Issue by stubailo** [jimkyndemeyer/js-graphql-language-service#2]
Hi!

I'm working on an ESLint plugin to validate queries here: https://github.com/apollostack/eslint-plugin-graphql

And my colleague @mquandalle is working on a VSCode plugin as well: https://github.com/apollostack/vscode-graphql

Afterwards, we're probably going to end up building some of the same completion features you've enabled in https://github.com/jimkyndemeyer/js-graphql-intellij-plugin

Curious if this is something you find useful or interesting, and if there's anything you ran into along the way that could help us achieve this more easily! For example, it's not clear what the best way to get the schema is - from a URL, JSON file, etc.

And if we are building for editors which natively support JS, is there a benefit to using a service, or do you think it would be better to just build the functionality into the plugin directly?

**Comment by jimkyndemeyer** [comment]
Hi.

Nice to hear that the Apollo stack is now moving into tooling as well.

The primary reason for creating a NodeJS-based language service was to leverage Facebook's investment in JavaScript from within a Java environment -- without having to re-invent the wheel, and without having to play catch up when the GraphQL spec changes over time.

If you're in a JS environment, I would say that a separate NodeJS process and the protocol that this requires is unnecessary. It adds overhead and deployment complexity, but in my case with IntelliJ that overhead was well worth it and proved "fast enough".

I don't know the parser and lexer infrastructure in vscode, but graphql-js won't help you there since it bails whenever a valid AST can not be produced -- which is 99% of the time in a live editor. This is where [codemirror-graphql](https://github.com/graphql/codemirror-graphql) proved useful, since it has built-in error recovery etc. This language service is simply a very thin wrapper around the codemirror mode, linter, and hinter.

Regarding the schema, and how to load it, I added the URL support since it proved useful for quickly experimenting and querying against existing endpoints. In my daily work though, I simply point towards a local schema.json which the language service then watches for changes.

Let me know if there's anything else.

Cheers,
Jim.

**Comment by jimkyndemeyer** [comment]
I did some more reading on vscode, and it appears that they actually use language servers. However, from their own example, they have their own API to do the actual implementation:

https://github.com/Microsoft/vscode-languageserver-node-example/blob/master/server/src/server.ts#L7-L13

I think mixing that approach with the simple JSON protocol in this project would be a bad fit in a single project. But feel free to use the code in this project as inspiration if it helps.

**Comment by stubailo** [comment]
Thanks for the detailed response! I think the knowledge you shared will be really helpful, especially the part about recovering from parse errors.
